# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55eb9075c1d89450bf3523074df21cf3461b4447ca16484ff2e750d9f1dcec81e2271caff23b22552af49c623b5575d891480ff511cf8b8a9d46e6c58c520bb4

test:
  secret_key_base: c57203bc1b5c7139a5d39a6b9f790ba398ae228ccf3d2d4ce8abe66b9b4e43ecf0b633a56bf011f2c0960530c36aae4c6c96ed32b2c8c8a66ea9fc7e3f153d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
